language:
    - node_js
node_js:
    - 9.2.1
branches:
    only:
    - master
    - develop
services:
    - mongodb
before_script:
    - npm install
script:
    - npm run all-test-travis
    - sonar-scanner -Dsonar.projectKey=nb24df435klvn5asd8235 -Dsonar.organization=s2a0r1a8 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=30dcc16a7e4147bf556ea1249f152886bd03dc13


