# Units
units:
- &unit0 #ROOT
    code: 50
    name: Unidad0 # ROOT
- &unit1
    code: 51
    name: Unidad1 #INHERIT
- &unit2
    code: 52
    name: Unidad2 #INHERIT
- &unit3
    code: 53
    name: Unidad3 #COMPOSE
- &unit4
    code: 54
    name: Unidad4 #COMPOSE
- &unit5
    code: 55
    name: Unidad5 #USE
- &unit6
    code: 56
    name: Unidad6 #USE
- &unit7
    code: 57
    name: Unidad7 #ASOCIATION
- &unit8
    code: 58
    name: Unidad8 #ASOCIATION
- &unit9
    code: 59
    name: Unidad9 #NO_RELATIONED
- &unit10
    code: 60
    name: Unidad10 #NO_RELATIONED
- &unit11
    code: 61
    name: Unidad11 #INHERIT

# Relations
relations:
- &relation0
    type: INHERIT
    topUnit: *unit0
    lowerUnit: *unit1
    semantics: Nada
- &relation1
    type: INHERIT
    topUnit: *unit0
    lowerUnit: *unit2
    semantics: Nada
- &relation2
    type: COMPOSE
    topUnit: *unit1
    lowerUnit: *unit3
    semantics: Nada
- &relation3
    type: COMPOSE
    topUnit: *unit2
    lowerUnit: *unit4
    semantics: Nada
- &relation4
    type: USE
    topUnit: *unit1
    lowerUnit: *unit5
    semantics: Nada
- &relation5
    type: USE
    topUnit: *unit2
    lowerUnit: *unit6
    semantics: Nada
- &relation6
    type: ASOCIATION
    topUnit: *unit1
    lowerUnit: *unit7
    semantics: Nada
- &relation7
    type: ASOCIATION
    topUnit: *unit2
    lowerUnit: *unit8
    semantics: Nada
- &relation11
    type: INHERIT
    topUnit: *unit0
    lowerUnit: *unit11
    semantics: Pelidiosa
