# Units
units:
- &unit0 #ROOT
    _id: {$oid: "161d87b8b260cf35147998ca"}
    code: 50
    name: Unidad0 # ROOT
- &unit1
    _id: {$oid: "261d87b8b260cf35147998ca"}
    code: 51
    name: Unidad1 #INHERIT
- &unit2
    _id: {$oid: "361d87b8b260cf35147998ca"}
    code: 52
    name: Unidad2 #INHERIT
- &unit3
    _id: {$oid: "461d87b8b260cf35147998ca"}
    code: 53
    name: Unidad3 #COMPOSE
- &unit4
    _id: {$oid: "561d87b8b260cf35147998ca"}
    code: 54
    name: Unidad4 #COMPOSE
- &unit5
    _id: {$oid: "661d87b8b260cf35147998ca"}
    code: 55
    name: Unidad5 #USE
- &unit6
    _id: {$oid: "761d87b8b260cf35147998ca"}
    code: 56
    name: Unidad6 #USE
- &unit7
    _id: {$oid: "861d87b8b260cf35147998ca"}
    code: 57
    name: Unidad7 #ASOCIATION
- &unit8
    _id: {$oid: "961d87b8b260cf35147998ca"}
    code: 58
    name: Unidad8 #ASOCIATION
- &unit9
    _id: {$oid: "221d87b8b260cf35147998ca"}
    code: 59
    name: Unidad9 #NO_RELATIONED
- &unit10
    _id: {$oid: "331d87b8b260cf35147998ca"}
    code: 60
    name: Unidad10 #NO_RELATIONED
- &unit11
    _id: {$oid: "441d87b8b260cf35147998ca"}
    code: 61
    name: Unidad11 #INHERIT

# Relations
relations:
- &relation0
    type: INHERIT
    topUnit: {$oid: "161d87b8b260cf35147998ca"} #unit0
    lowerUnit: {$oid: "261d87b8b260cf35147998ca"} #unit1
    semantics: Nada
- &relation1
    type: INHERIT
    topUnit: {$oid: "161d87b8b260cf35147998ca"} #unit0
    lowerUnit: {$oid: "361d87b8b260cf35147998ca"} #unit2
    semantics: Nada
- &relation2
    type: COMPOSE
    topUnit: {$oid: "261d87b8b260cf35147998ca"} #unit1
    lowerUnit: {$oid: "461d87b8b260cf35147998ca"} #unit3
    semantics: Nada
- &relation3
    type: COMPOSE
    topUnit: {$oid: "361d87b8b260cf35147998ca"} #unit2
    lowerUnit: {$oid: "561d87b8b260cf35147998ca"} #unit4
    semantics: Nada
- &relation4
    type: USE
    topUnit: {$oid: "261d87b8b260cf35147998ca"} #unit1
    lowerUnit: {$oid: "661d87b8b260cf35147998ca"} #unit5
    semantics: Nada
- &relation5
    type: USE
    topUnit: {$oid: "361d87b8b260cf35147998ca"} #unit2
    lowerUnit: {$oid: "761d87b8b260cf35147998ca"} #unit6
    semantics: Nada
- &relation6
    type: ASOCIATION
    topUnit: {$oid: "261d87b8b260cf35147998ca"} #unit1
    lowerUnit: {$oid: "861d87b8b260cf35147998ca"} #unit7
    semantics: Nada
- &relation7
    type: ASOCIATION
    topUnit: {$oid: "361d87b8b260cf35147998ca"} #unit2
    lowerUnit: {$oid: "961d87b8b260cf35147998ca"} #unit8
    semantics: Nada
- &relation11
    type: INHERIT
    topUnit: {$oid: "161d87b8b260cf35147998ca"} #unit0
    lowerUnit: {$oid: "441d87b8b260cf35147998ca"} #unit11
    semantics: Pelidiosa
