#Interaction
interactions:
    - &interaction1
        _id: {$oid: "361d87b8b230cf35177998c0"}
        formulation: I1
        kind: Exercise
        solution: [ ]
    - &interaction2
        _id: {$oid: "361d87b8b230cf35177998c1"}
        url: bleble
        kind: Video

# Justifications
justifications:
- &justification0
    _id: {$oid: "101d87b8b230cf35177998ca"}
    isCorrect: false
    text: El descubrimiento de la luna fue en 1999
- &justification1
    _id: {$oid: "111d87b8b230cf35177998ca"}
    isCorrect: true
    text: El descubrimiento de la luna fue en 1969
- &justification2
    _id: {$oid: "121d87b8b230cf35177998ca"}
    isCorrect: false
    text: El descubrimiento de la luna fue en 2005
- &justification3
    _id: {$oid: "131d87b8b230cf35177998ca"}
    isCorrect: true
    text: El agua es una molecula formada por dos moleculas de oxigeno y una de hidrogeno

# Solutions
solutions:
- &solution0
    _id: {$oid: "361d87b8b230cf35177998ca"}
    isCorrect: false
    text: 1974
    justifications: [{$oid: "101d87b8b230cf35177998ca"}, {$oid: "111d87b8b230cf35177998ca"}, {$oid: "121d87b8b230cf35177998ca"}]
- &solution1
    _id: {$oid: "461d87b8b230cf35177998cb"}
    isCorrect: true
    text: La oveja Dolly
    justifications: []
- &solution2
    _id: {$oid: "561d87b8b230cf35177998cc"}
    isCorrect: true
    text: La formula del agua H20
    justifications: [{$oid: "131d87b8b230cf35177998ca"}]

# Units
units:
- &unit0 #ROOT
    _id: {$oid: "161d87b8b260cf35147998ca"}
    code: 50
    name: Unidad50 # ROOT
- &unit1
    _id: {$oid: "261d87b8b260cf35147998ca"}
    code: 51
    name: Unidad51 #INHERIT
- &unit2
    _id: {$oid: "361d87b8b260cf35147998ca"}
    code: 52
    name: Unidad52 #INHERIT
- &unit3
    _id: {$oid: "461d87b8b260cf35147998ca"}
    code: 53
    name: Unidad53 #COMPOSE
- &unit4
    _id: {$oid: "561d87b8b260cf35147998ca"}
    code: 54
    name: Unidad54 #COMPOSE
- &unit5
    _id: {$oid: "661d87b8b260cf35147998ca"}
    code: 55
    name: Unidad55 #USE
- &unit6
    _id: {$oid: "761d87b8b260cf35147998ca"}
    code: 56
    name: Unidad56 #USE
- &unit7
    _id: {$oid: "861d87b8b260cf35147998ca"}
    code: 57
    name: Unidad57 #ASSOCIATION
- &unit8
    _id: {$oid: "961d87b8b260cf35147998ca"}
    code: 58
    name: Unidad58 #ASSOCIATION
- &unit9
    _id: {$oid: "221d87b8b260cf35147998ca"}
    code: 59
    name: Unidad59 #NO_RELATIONED
- &unit10
    _id: {$oid: "331d87b8b260cf35147998ca"}
    code: 60
    name: Unidad60 #NO_RELATIONED
- &unit11
    _id: {$oid: "441d87b8b260cf35147998ca"}
    code: 61
    name: Unidad61 #INHERIT

# Relations
relations:
- &relation0
    type: INHERIT
    topUnit: {$oid: "161d87b8b260cf35147998ca"} #unit50
    lowerUnit: {$oid: "261d87b8b260cf35147998ca"} #unit51
    semantics: Nada
- &relation1
    type: INHERIT
    topUnit: {$oid: "161d87b8b260cf35147998ca"} #unit50
    lowerUnit: {$oid: "361d87b8b260cf35147998ca"} #unit52
    semantics: Nada
- &relation2
    type: COMPOSE
    topUnit: {$oid: "261d87b8b260cf35147998ca"} #unit51
    lowerUnit: {$oid: "461d87b8b260cf35147998ca"} #unit53
    semantics: Nada
    cardinalTopUnit: 1
- &relation3
    type: COMPOSE
    topUnit: {$oid: "361d87b8b260cf35147998ca"} #unit52
    lowerUnit: {$oid: "561d87b8b260cf35147998ca"} #unit54
    semantics: Nada
    cardinalTopUnit: 1
- &relation4
    type: USE
    topUnit: {$oid: "261d87b8b260cf35147998ca"} #unit51
    lowerUnit: {$oid: "661d87b8b260cf35147998ca"} #unit55
    semantics: Nada
    cardinalTopUnit: 1
    cardinalLowerUnit: n
- &relation5
    type: USE
    topUnit: {$oid: "361d87b8b260cf35147998ca"} #unit52
    lowerUnit: {$oid: "761d87b8b260cf35147998ca"} #unit56
    semantics: Nada
    cardinalTopUnit: 1
    cardinalLowerUnit: n
- &relation6
    type: ASSOCIATION
    topUnit: {$oid: "261d87b8b260cf35147998ca"} #unit51
    lowerUnit: {$oid: "861d87b8b260cf35147998ca"} #unit57
    semantics: Nada
    cardinalTopUnit: 1
    cardinalLowerUnit: n
- &relation7
    type: ASSOCIATION
    topUnit: {$oid: "361d87b8b260cf35147998ca"} #unit52
    lowerUnit: {$oid: "961d87b8b260cf35147998ca"} #unit58
    semantics: Nada
    cardinalTopUnit: 1
    cardinalLowerUnit: n
- &relation8
    type: INHERIT
    topUnit: {$oid: "161d87b8b260cf35147998ca"} #unit50
    lowerUnit: {$oid: "441d87b8b260cf35147998ca"} #unit61
    semantics: Pelidiosa

