# Units
units:
- &unit0 #ROOT
    _id: 0
    name: Unidad0
- &unit1  #INHERIT
    _id: 1
    name: Unidad1
- &unit2  #INHERIT
    _id: 2
    name: Unidad2
- &unit3 #COMPOSE
    _id: 3
    name: Unidad3
- &unit4 #COMPOSE
    _id: 4
    name: Unidad4
- &unit5 #USE
    _id: 5
    name: Unidad5
- &unit6 #USE
    _id: 6
    name: Unidad6
- &unit7 #ASOCIATION
    _id: 7
    name: Unidad7
- &unit8 #ASOCIATION
    _id: 8
    name: Unidad8
- &unit9 #NO_RELATIONED
    _id: 9
    name: Unidad9
- &unit10 #NO_RELATIONED
    _id: 10
    name: Unidad10

# Relations
relations:
- &relation0
    type: INHERIT
    topUnit: *unit0._id
    lowerUnit: *unit1._id
- &relation1
    type: INHERIT
    topUnit: *unit0._id
    lowerUnit: *unit2._id
- &relation2
    type: COMPOSE
    topUnit: *unit1._id
    lowerUnit: *unit3._id
- &relation3
    type: COMPOSE
    topUnit: *unit2._id
    lowerUnit: *unit4._id
- &relation4
    type: USE
    topUnit: *unit1._id
    lowerUnit: *unit5._id
- &relation5
    type: USE
    topUnit: *unit2._id
    lowerUnit: *unit6._id
- &relation6
    type: ASOCIATION
    topUnit: *unit1._id
    lowerUnit: *unit7._id
- &relation7
    type: ASOCIATION
    topUnit: *unit2._id
    lowerUnit: *unit8._id