# Units
units:
- &unit0 #ROOT
    _id: 0
    name: Unidad0 # ROOT
- &unit1
    _id: 1
    name: Unidad1 #INHERIT
- &unit2
    _id: 2
    name: Unidad2 #INHERIT
- &unit3
    _id: 3
    name: Unidad3 #COMPOSE
- &unit4
    _id: 4
    name: Unidad4 #COMPOSE
- &unit5
    _id: 5
    name: Unidad5 #USE
- &unit6
    _id: 6
    name: Unidad6 #USE
- &unit7
    _id: 7
    name: Unidad7 #ASOCIATION
- &unit8
    _id: 8
    name: Unidad8 #ASOCIATION
- &unit9
    _id: 9
    name: Unidad9 #NO_RELATIONED
- &unit10
    _id: 10
    name: Unidad10 #NO_RELATIONED
- &unit11
    _id: 11
    name: Unidad11 #INHERIT

# Relations
relations:
- &relation0
    type: INHERIT
    topUnit: 0
    lowerUnit: 1
    semantics: Nada
- &relation1
    type: INHERIT
    topUnit: 0
    lowerUnit: 2
    semantics: Nada
- &relation2
    type: COMPOSE
    topUnit: 1
    lowerUnit: 3
    semantics: Nada
- &relation3
    type: COMPOSE
    topUnit: 2
    lowerUnit: 4
    semantics: Nada
- &relation4
    type: USE
    topUnit: 1
    lowerUnit: 5
    semantics: Nada
- &relation5
    type: USE
    topUnit: 2
    lowerUnit: 6
    semantics: Nada
- &relation6
    type: ASOCIATION
    topUnit: 1
    lowerUnit: 7
    semantics: Nada
- &relation7
    type: ASOCIATION
    topUnit: 2
    lowerUnit: 8
    semantics: Nada
- &relation11
    type: INHERIT
    topUnit: 0
    lowerUnit: 11
    semantics: Pelidiosa
